<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" Version="2.1.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.5" />
    <PackageReference
      Include="Microsoft.Extensions.Configuration.EnvironmentVariables"
      Version="10.0.5"
    />
    <PackageReference
      Include="Microsoft.Extensions.Options.ConfigurationExtensions"
      Version="10.0.5"
    />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.5" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="Pgvector.EntityFrameworkCore" Version="0.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Postgres\Configurations\" />
    <Folder Include="Postgres\Repositories\" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="StarterKit.Core.Tests" />
    <InternalsVisibleTo Include="StarterKit.Data.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>
</Project>
