#!/usr/bin/env node
/**
 * PreToolUse hook (Write|Edit|MultiEdit|NotebookEdit) — refuse edits to files that are
 * generated, locked, or secret-bearing.
 *
 * Every rule here already exists in docs/standards/ as an instruction ("never hand-edit
 * the proxy", "npm is the only package manager"). An instruction an agent can forget is
 * a gate that does not exist, so this turns each one into a deny with the actual fix in
 * the message — the agent reads the reason and runs the generator instead.
 *
 * Fail-open on anything unexpected. Set SK_HOOK_GUARD=0 to disable.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';

/** Each rule: does this path match, and what should the agent do instead. */
const RULES = [
  {
    test: (p) => p.includes('/src/proxy/'),
    reason:
      'apps/*/src/proxy/** is generated by Orval from the backend OpenAPI schema — hand edits are ' +
      'overwritten on the next run. Change the backend controller/DTO, then run ' +
      '`npm run generate:proxy` (backend running) or `npm run generate:proxy:local`. ' +
      'See docs/standards/frontend.md § Proxy type safety.',
  },
  {
    test: (p) => p === 'package-lock.json',
    reason:
      'package-lock.json is npm-owned. Edit the relevant package.json and run `npm install` so the ' +
      'lockfile is regenerated consistently.',
  },
  {
    test: (p) => /\/Migrations\/.*(\.Designer\.cs|ModelSnapshot\.cs)$/.test(p),
    reason:
      'EF Core writes Migrations/*.Designer.cs and *ModelSnapshot.cs — editing them desynchronises ' +
      'the model snapshot from the migration history. Change the entity/configuration and run ' +
      '`dotnet ef migrations add <Name>`. See docs/standards/backend/auditing.md.',
  },
  {
    test: (p) => p.startsWith('graphify-out/'),
    reason: 'graphify-out/** is generated. Rebuild it with `/graphify` in Copilot Chat instead.',
  },
  {
    test: (p) => /(^|\/)\.env(\.|$)/.test(p) && !p.endsWith('.example'),
    reason:
      'Real .env files hold live credentials and are gitignored — an agent must not write them. ' +
      'Document the variable in .env.example and ask the user to set the value locally ' +
      '(or use `/pull-secrets`).',
  },
];

function deny(reason) {
  process.stdout.write(
    `${JSON.stringify({
      hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        permissionDecision: 'deny',
        permissionDecisionReason: reason,
      },
    })}\n`,
  );
}

function main() {
  if (process.env.SK_HOOK_GUARD === '0') return;

  const input = JSON.parse(readFileSync(0, 'utf8'));
  const filePath = input?.tool_input?.file_path ?? input?.tool_input?.notebook_path;
  if (!filePath) return;

  const cwd = input?.cwd ?? process.cwd();
  const relativePath = path.relative(cwd, filePath).split(path.sep).join('/');
  if (relativePath.startsWith('..') || path.isAbsolute(relativePath)) return;

  const rule = RULES.find((candidate) => candidate.test(relativePath));
  if (rule) deny(`Blocked write to ${relativePath}. ${rule.reason}`);
}

try {
  main();
} catch {
  // Fail open — a guard that cannot read its input must not block ordinary edits.
}
