#!/usr/bin/env node
// Pulls E2E secrets tagged app=e2e from kv-starterkit-dev into .env.e2e.
//
// Use this when running Playwright directly (npx playwright test) so that
// test credentials are available without manually maintaining .env.e2e.
//
// The orchestrated runner (run-e2e.sh) and CI pipeline fetch from Key Vault
// at runtime and export directly as env vars — no file needed.
//
// Run: npm run pull:env  (requires az cli authenticated — run `az login` first)

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ENV_FILE = join(__dirname, '..', '.env.e2e');
const KV = 'kv-starterkit-dev';

function az(args) {
  return execSync(`az ${args}`, { encoding: 'utf8' }).trimEnd();
}

try {
  az('version --output none');
} catch {
  console.error(
    'Error: Azure CLI (az) is not installed or not in PATH. See https://aka.ms/install-azure-cli',
  );
  process.exit(1);
}

console.log(`Fetching E2E secrets from Key Vault (${KV}, tag: app=e2e)...`);

const namesJson = az(
  `keyvault secret list --vault-name ${KV} --query "[?tags.app=='e2e'].name" -o json`,
);
const names = JSON.parse(namesJson);

// Zero matches is a valid state on a young vault — e2e credentials may not be provisioned
// yet (they depend on real auth-provider accounts). Warn and write a header-only file so
// `/pull-secrets` completes cleanly rather than erroring. A hard failure is reserved for
// real errors (az not logged in, vault unreachable) handled above.
if (!names.length) {
  console.warn(`  ⚠ No secrets tagged app=e2e in ${KV} yet — writing an empty .env.e2e.`);
}

const lines = [
  '# Auto-generated by npm run pull:env — do not edit manually.',
  '# Re-run pull:env to refresh. Source: Azure Key Vault (kv-starterkit-dev, tag: app=e2e)',
  '',
];

for (const name of names) {
  const value = az(`keyvault secret show --vault-name ${KV} --name ${name} --query value -o tsv`);
  // Auto-map: kebab-case name → UPPER_SNAKE_CASE (e.g. e2e-admin-email → E2E_ADMIN_EMAIL).
  const varName = name.toUpperCase().replace(/-/g, '_');
  lines.push(`${varName}=${value}`);
}

writeFileSync(ENV_FILE, `${lines.join('\n')}\n`, 'utf8');
console.log(`Wrote ${names.length} secret(s) to ${ENV_FILE}`);
